# -*- coding: utf-8 -*-
"""Logistic_Regression_MPG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mqtei19650Rvxj7H1ku-kJrwEX_YCqN3
"""

# ================================
# Logistic Regression (from scratch) — Skeleton
# ================================

# 0) Imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


# 1) Load / prepare data
# --------------------------------------------------
# Assumptions (edit as needed):
#   - Binary classification with labels in {0,1}
#   - X is an (m, n) feature matrix (no bias column yet)
#   - y is an (m,) label vector

# TODO: replace with your real data loading
def load_data(file_path):
    # Read the CSV, skipping the complex header and using the first row as data
    # We will select columns by index due to the irregular header
    df = pd.read_csv(file_path, header=1) # Assuming the actual data starts from the second row

    # Based on the provided header structure:
    # 'MPG' seems to be the 10th column (index 9)
    # Feature columns: Pts/100 (index 10), ORtg (index 13), eRO (index 30), eRD (index 31), eRT (index 32), WAR (index 33),
    # PER (index 27), WS/48 (index 28), BPM (index 31), On/Off (index 36) - Note: BPM index seems repeated, double check your data
    # Let's use the column names based on your previous request and assume the header=1 fixes the reading issue for these names
    # If KeyError persists, we will revert to index-based selection.

    # Define the target variable based on MPG > 30
    # Replace 'MPG' with your actual MPG column name if it's different
    df['Target'] = (df['MPG'] > 30).astype(int)
    target_column = 'Target'

    # Replace the list below with the names of your 12 feature columns
    feature_columns = ['Pts/100', 'ORtg', 'eRO', 'eRD', 'eRT', 'WAR',
                       'PER', 'WS/48', 'BPM', 'On/Off']


    X = df[feature_columns].values
    y = df[target_column].values


    # (Optional) Feature scaling — often helps training stability
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)


    # (Optional) Split the dataset into training and test
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

    return X_train, X_test, y_train, y_test, scaler


# TODO: Call load_data with your file path and assign to X and y
file_path_1 = r"statsheet.csv"
X_train, X_test, y_train, y_test, scaler = load_data(file_path_1)


X = X_train
y = y_train
m = X.shape[0]


# bias column (x0 = 1)
X = np.column_stack([np.ones(m), X])  # shape: (m, n+1)
n_with_bias = X.shape[1]


# 2) Utility functions: sigmoid, loss, gradient, prediction
# --------------------------------------------------
def sigmoid(z):
    # σ(z) = 1 / (1 + e^-z)
    # TODO: Complete the sigmoid function
    return 1 / (1 + np.exp(-z))

def predict_proba(X, w):
    # p = σ(Xw)
    # TODO: Complete the predict probability function
    return sigmoid(X @ w)

def binary_cross_entropy(y_true, y_prob, eps=1e-12):
    # Log-loss = - [ y log(p) + (1-y) log(1-p) ]
    # You might need to restrict the values using np.clip
    # TODO: Complete the binary cross entropy function
    y_prob = np.clip(y_prob, eps, 1 - eps)
    return -np.mean(y_true * np.log(y_prob) + (1 - y_true) * np.log(1 - y_prob))

def gradient(X, y_true, y_prob):
    # ∂J/∂w = (1/m) X^T (p - y)
    # TODO: Complete the gradient descent function
    m = X.shape[0]
    return (1/m) * X.T @ (y_prob - y_true)


# 3) Initialize parameters
# --------------------------------------------------
# TODO: set the initial values for the parameters
w = np.zeros(n_with_bias)

# 4) Hyperparameters
# --------------------------------------------------
# TODO: set learning_rate and num_iterations
learning_rate = 0.01
num_iterations = 1000

# For tracking
cost_history = []


# 5) Gradient Descent loop
# --------------------------------------------------
for i in range(num_iterations):
    # TODO: Forward pass: compute probabilities
    y_prob = predict_proba(X, w)

    # TODO: Compute loss (log-loss / cross-entropy)
    cost = binary_cross_entropy(y, y_prob)
    cost_history.append(cost)

    # TODO: Backward pass: compute gradient
    grad = gradient(X, y, y_prob)

    # TODO Parameter update
    w -= learning_rate * grad


# 6) Final parameters
# --------------------------------------------------
print("Final parameters (w):")
print(w)  # w[0] is bias term


# 7) Plot: Cost vs Iterations
# --------------------------------------------------
plt.figure()
plt.plot(range(len(cost_history)), cost_history)
plt.xlabel("Iteration")
plt.ylabel("Cost (Log-Loss)")
plt.title("Training: Cost vs. Iterations")
plt.grid(True)
plt.show()


# 8) Plot: Cost vs 3 of the most important parameters
# --------------------------------------------------
# Idea: pick 3 parameters (excluding bias) by magnitude after training,
# then sweep each parameter around its learned value while holding others fixed,
# and plot the (1D) cost curve for each.
#At the end of training, you have a weight vector w (parameters). You also have a
# cost function 𝐽 ( 𝑤)
#J(w), which tells you how good or bad those weights are.

#Normally, we look at cost vs iterations (how the loss decreases over time). But sometimes it’s useful to see:
# “What happens to the cost if I wiggle just one parameter, while keeping all others fixed?”

# That’s what the sweep does.
#For each candidate value in the sweep, we create a temporary weight vector w_tmp.
# We replace the chosen parameter with val.
# Then we compute the cost 𝐽 (𝑤_tmp ) using the same dataset.
# Append that cost to a list.

#We plot:

#x-axis: the parameter’s value (from the sweep)

#y-axis: the cost computed at that parameter value

#This shows the “sensitivity curve” of the cost with respect to that parameter.

# Identify top-3 parameters by |w| (excluding bias at index 0)

param_indices = np.argsort(np.abs(w[1:]))[::-1][:3] + 1  # shift by 1 to skip bias
print("Plotting cost sensitivity for parameter indices:", param_indices)

def compute_cost_given_w(mod_w):
    # Helper to compute cost for a modified parameter vector
    y_hat_mod = predict_proba(X, mod_w)
    return binary_cross_entropy(y, y_hat_mod)

# For each chosen parameter, sweep values and compute cost
for idx in param_indices:
    center = w[idx]
    #  choose a sensible sweep range; here: ±1.0 around the trained value
    sweep = np.linspace(center - 1.0, center + 1.0, 60)

    costs = []
    for val in sweep:
        w_tmp = w.copy()
        w_tmp[idx] = val
        costs.append(compute_cost_given_w(w_tmp))

    plt.figure()
    plt.plot(sweep, costs)
    plt.xlabel(f"Parameter w[{idx}]")
    plt.ylabel("Cost (Log-Loss)")
    plt.title(f"Cost vs Parameter w[{idx}] (holding others fixed)")
    plt.grid(True)
    plt.show()


# 9) (Optional) Inference helper
# --------------------------------------------------
def predict_label(X_new, w, threshold=0.5):
    # Returns 0/1 predictions based on threshold
    return (predict_proba(X_new, w) >= threshold).astype(int)

# Example usage (remove in production):
# preds = predict_label(X, w)
# accuracy = (preds == y).mean()/
# print("Training accuracy (for reference only):", accuracy)

# Print model details and results

# Initial parameters (theta) - Before training, w was initialized to zeros
initial_theta = np.zeros(n_with_bias)
print("Initial parameters (theta):")
print(initial_theta)

# Initial loss - Calculate cost with initial parameters
initial_y_prob = predict_proba(X, initial_theta)
initial_loss = binary_cross_entropy(y, initial_y_prob)
print("\nInitial Loss:", initial_loss)

# Learning rate
print("\nLearning Rate:", learning_rate)

# Number of iterations
print("Number of Iterations:", num_iterations)

# Number of features (including bias)
print("Number of Features (including bias):", n_with_bias)

# Final parameters (theta) - This is the 'w' after training
print("\nFinal parameters (theta):")
print(w)

# Final loss - The last value in the cost_history
final_loss = cost_history[-1]
print("\nFinal Loss:", final_loss)
